import { Inter, Space_Grotesk, Noto_Sans_Devanagari } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { AuthProvider } from '@/context/auth-context';
import { Toaster } from '@/components/ui/toaster';
import { SubscriptionProvider } from '@/context/subscription-context';
import { LanguageProvider } from '@/context/language-context';

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  variable: '--font-space-grotesk',
});

const notoDevanagari = Noto_Sans_Devanagari({
  subsets: ['latin'],
  variable: '--font-noto-devanagari',
  weight: ['400', '700'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn('font-body antialiased', inter.variable, spaceGrotesk.variable, notoDevanagari.variable)}>
        <LanguageProvider>
          <SubscriptionProvider>
            <AuthProvider>
              {children}
            </AuthProvider>
          </SubscriptionProvider>
        </LanguageProvider>
        <Toaster />
      </body>
    </html>
  );
}
